### ISSUE TITLE
Python dependency is missing in the Getting Started section

### ISSUE THREAD

**Issue by doumazane** [BIOP/abba_python#10]
Hi, 
Thank you for developing Abba, it's a very nice tool.

I have a concern about the [getting started section](https://github.com/BIOP/abba_python/#getting-started).
The instructions are as follows: 
- create an environment *without python*
- activate it
- call `pip install abba-python`

On my system, this results in installing **all abba-python dependencies in system's pip.**

I assume this is not the intended behavior and it may result in very unexpected problems.

I would suggest adding python and using a YML file that can be passed to conda, such as:

```yaml
# Run conda env create -f <path to this file> to create the environment
# Run conda env update -f <path to this file> to update the environment
name: abba-env
channels:
  - conda-forge
dependencies:
  - openjdk=8
  - python=3.10 
  - pip
  - ipykernel
  - ipywidgets
  - maven
  - pip:
    - abba-python 
```

(i had to install maven)
